-- ============================================================
-- SEED DATA — 20 entries per table
-- Jalankan di Supabase SQL Editor setelah schema
-- ============================================================

-- ── PROJECTS (20) ─────────────────────────────────────────
INSERT INTO projects (title, subtitle, slug, category, location, area, duration, year, status, client, description, full_description, cover_image, images, tags, featured, value) VALUES
('Villa Puncak Elevasi', 'Luxury Mountain Retreat', 'villa-puncak-elevasi', 'Residensial Mewah', 'Puncak, Bogor', '1.200 m²', '18 Bulan', 2024, 'completed', 'Private Client', 'Villa mewah bergaya kontemporer tropis dengan pemandangan pegunungan.', 'Villa kontemporer tropis di atas bukit dengan view 360 derajat ke Gunung Gede dan Pangrango. Material batu alam lokal dipadukan teknologi konstruksi modern.', null, '{}', '{"Kontemporer","Tropis","Mewah"}', true, 'Rp 12 Miliar'),
('Nexus Business Tower', 'Grade-A Commercial Office', 'nexus-business-tower', 'Komersial', 'SCBD, Jakarta Selatan', '45.000 m²', '36 Bulan', 2023, 'completed', 'PT Nexus Property', 'Gedung perkantoran Grade-A 32 lantai dengan sertifikasi LEED Gold.', 'Landmark baru di SCBD Jakarta. 32 lantai dengan fasad double-skin glass dan sistem smart building terintegrasi. Sertifikasi LEED Gold.', null, '{}', '{"High-Rise","Green Building","LEED"}', true, 'Rp 280 Miliar'),
('Uluwatu Cliff Resort', 'Boutique Beachfront Resort', 'uluwatu-cliff-resort', 'Hospitality', 'Uluwatu, Bali', '8.500 m²', '24 Bulan', 2023, 'completed', 'Horizon Hospitality Group', 'Resort butik eksklusif di tebing Uluwatu dengan 45 villa private.', '45 villa private di tebing Uluwatu menghadap Samudra Hindia. Konstruksi micro-pile di atas tebing dengan material tahan korosi.', null, '{}', '{"Resort","Cliff Side","Bali"}', true, 'Rp 95 Miliar'),
('Green Valley Residence', 'Eco-Friendly Housing', 'green-valley-residence', 'Perumahan', 'Serpong, Tangerang', '25.000 m²', '30 Bulan', 2024, 'ongoing', 'PT Green Land Developer', 'Perumahan eco-friendly 120 unit dengan solar panel dan daur ulang air.', 'Kawasan perumahan masa depan dengan panel surya, pengolahan air hujan, dan taman vertikal di setiap unit. Car-free zone dengan jalur sepeda.', null, '{}', '{"Eco-Friendly","Solar","Smart Home"}', true, 'Rp 180 Miliar'),
('Heritage Grand Dining', 'Fine Dining Restaurant', 'heritage-grand-dining', 'Komersial', 'Menteng, Jakarta Pusat', '2.800 m²', '8 Bulan', 2023, 'completed', 'PT Kuliner Nusantara', 'Restoran fine dining dengan konsep heritage kolonial Belanda.', 'Renovasi bangunan cagar budaya 1920-an menjadi restoran premium. Plafon ukiran kayu direstorasi, sistem MEP tersembunyi sempurna.', null, '{}', '{"Heritage","Restorasi","Interior"}', false, 'Rp 28 Miliar'),
('Flyover Akses Pelabuhan', 'Infrastruktur Jalan Layang', 'flyover-akses-pelabuhan', 'Infrastruktur', 'Tanjung Priok, Jakarta', '2.3 km', '20 Bulan', 2022, 'completed', 'Kementerian PUPR', 'Jalan layang akses pelabuhan sepanjang 2,3 km.', 'Flyover kritis untuk arus logistik nasional. Precast Segmental Box Girder, konstruksi 24 jam tanpa ganggu lalu lintas.', null, '{}', '{"Infrastruktur","Jalan Layang","Pemerintah"}', false, 'Rp 340 Miliar'),
('Apartemen The Pinnacle', 'Luxury High-Rise Apartment', 'apartemen-pinnacle', 'Residensial Mewah', 'Sudirman, Jakarta', '62.000 m²', '42 Bulan', 2024, 'ongoing', 'PT Pinnacle Realty', 'Apartemen mewah 48 lantai di koridor Sudirman dengan 320 unit.', 'Tower apartemen premium dengan sky garden di lantai 25, infinity pool, dan concierge service 24 jam.', null, '{}', '{"Apartemen","Luxury","High-Rise"}', false, 'Rp 520 Miliar'),
('Kawasan Industri Karawang', 'Industrial Estate Development', 'kawasan-industri-karawang', 'Infrastruktur', 'Karawang, Jawa Barat', '150 Ha', '48 Bulan', 2023, 'ongoing', 'PT KIK Development', 'Pengembangan kawasan industri terintegrasi seluas 150 hektar.', 'Kawasan industri modern dengan IPAL, sistem utilitas terpadu, dan akses tol langsung. Standar internasional untuk tenant multinasional.', null, '{}', '{"Industri","Kawasan","Infrastruktur"}', false, 'Rp 1.2 Triliun'),
('Masjid Agung Bekasi', 'Grand Mosque Construction', 'masjid-agung-bekasi', 'Fasilitas Publik', 'Bekasi, Jawa Barat', '12.000 m²', '28 Bulan', 2022, 'completed', 'Pemerintah Kota Bekasi', 'Masjid agung kapasitas 10.000 jamaah dengan arsitektur Islami modern.', 'Masjid dengan kubah utama 35 meter, menara kembar 60 meter, dan sistem akustik premium. Material granit impor dan ornamen tembaga.', null, '{}', '{"Masjid","Publik","Islami"}', false, 'Rp 85 Miliar'),
('The Pavilion Villa Seminyak', 'Boutique Villa Complex', 'pavilion-villa-seminyak', 'Hospitality', 'Seminyak, Bali', '4.200 m²', '16 Bulan', 2024, 'completed', 'Pavilion Group', 'Kompleks 12 villa butik premium di jantung Seminyak.', '12 villa dengan konsep open-air tropical. Setiap villa punya private pool, outdoor shower, dan butler service eksklusif.', null, '{}', '{"Villa","Bali","Boutique"}', false, 'Rp 48 Miliar'),
('Rumah Sakit Siloam Bogor', 'Healthcare Facility', 'rs-siloam-bogor', 'Fasilitas Kesehatan', 'Bogor, Jawa Barat', '28.000 m²', '36 Bulan', 2023, 'completed', 'Siloam Hospitals Group', 'Rumah sakit 12 lantai berkapasitas 400 tempat tidur.', 'Fasilitas kesehatan modern dengan standar internasional JCI. Sistem HVAC khusus medis, ruang operasi bertekanan positif, dan ICU berteknologi tinggi.', null, '{}', '{"Kesehatan","Rumah Sakit","Fasilitas"}', false, 'Rp 195 Miliar'),
('Ruko Premium Alam Sutera', 'Commercial Shophouse', 'ruko-alam-sutera', 'Komersial', 'Alam Sutera, Tangerang', '8.500 m²', '14 Bulan', 2023, 'completed', 'PT Alam Sutera Realty', '50 unit ruko premium 4 lantai dengan desain kontemporer.', '50 ruko premium dengan fasad kaca dan aluminium modern. Basement parkir, genset backup, dan sistem keamanan CCTV 24 jam.', null, '{}', '{"Ruko","Komersial","Premium"}', false, 'Rp 62 Miliar'),
('Sekolah Internasional BSD', 'International School', 'sekolah-internasional-bsd', 'Pendidikan', 'BSD City, Tangerang', '18.000 m²', '24 Bulan', 2022, 'completed', 'Global Education Group', 'Sekolah internasional bertaraf Cambridge untuk 2.000 siswa.', 'Kampus modern dengan laboratorium sains, studio seni, amphiteater outdoor, dan lapangan olahraga standar internasional.', null, '{}', '{"Pendidikan","Sekolah","Internasional"}', false, 'Rp 140 Miliar'),
('Hotel Bintang Lima Labuan Bajo', 'Five-Star Resort Hotel', 'hotel-labuan-bajo', 'Hospitality', 'Labuan Bajo, NTT', '15.000 m²', '30 Bulan', 2024, 'ongoing', 'Archipelago International', 'Hotel bintang lima dengan 180 kamar menghadap Laut Flores.', 'Resort premium dengan infinity pool 80 meter, restoran tepi laut, spa bertaraf internasional, dan fasilitas selam profesional.', null, '{}', '{"Hotel","Bintang Lima","Labuan Bajo"}', false, 'Rp 280 Miliar'),
('Gudang Logistik Cikarang', 'Logistics Warehouse', 'gudang-logistik-cikarang', 'Industri', 'Cikarang, Bekasi', '35.000 m²', '12 Bulan', 2023, 'completed', 'PT Logindo Samudramakmur', 'Gudang logistik modern seluas 35.000 m² dengan sistem otomasi.', 'Fasilitas logistik berteknologi tinggi dengan sistem conveyor otomatis, rak penyimpanan tinggi 15 meter, dan loading dock 40 pintu.', null, '{}', '{"Gudang","Logistik","Industri"}', false, 'Rp 75 Miliar'),
('Perumahan Bukit Sentul', 'Gated Community', 'perumahan-bukit-sentul', 'Perumahan', 'Sentul, Bogor', '40 Ha', '36 Bulan', 2023, 'ongoing', 'PT Bukit Sentul', 'Perumahan gated community 500 unit di kaki gunung Sentul.', 'Perumahan eksklusif dengan clubhouse, kolam renang olimpik, lapangan golf 9 hole, dan sistem keamanan 24 jam.', null, '{}', '{"Perumahan","Gated","Premium"}', false, 'Rp 450 Miliar'),
('Jembatan Kali Bekasi', 'Bridge Infrastructure', 'jembatan-kali-bekasi', 'Infrastruktur', 'Bekasi, Jawa Barat', '320 m', '18 Bulan', 2022, 'completed', 'Dinas PUPR Bekasi', 'Jembatan beton prategang sepanjang 320 meter.', 'Jembatan cable-stayed dengan dua pylon 45 meter. Kapasitas beban 25 ton, lebar 12 meter, dan masa layan 100 tahun.', null, '{}', '{"Jembatan","Infrastruktur","Pemerintah"}', false, 'Rp 95 Miliar'),
('Gedung Pemerintahan Depok', 'Government Office Building', 'gedung-pemerintahan-depok', 'Pemerintah', 'Depok, Jawa Barat', '22.000 m²', '28 Bulan', 2023, 'completed', 'Pemerintah Kota Depok', 'Gedung pemerintahan 12 lantai sebagai pusat pelayanan publik.', 'Pusat layanan publik terpadu dengan 800 ruang kerja, aula 2.000 kapasitas, dan sistem e-government terintegrasi.', null, '{}', '{"Pemerintah","Gedung","Publik"}', false, 'Rp 165 Miliar'),
('Studio Film Cikini', 'Film Production Studio', 'studio-film-cikini', 'Komersial', 'Cikini, Jakarta Pusat', '5.500 m²', '10 Bulan', 2024, 'completed', 'Produksi Nusantara Films', 'Studio produksi film berstandar internasional dengan 3 stage utama.', 'Studio film modern dengan stage terbesar 2.400 m², sistem pencahayaan LED motorized, dan post-production suite berteknologi tinggi.', null, '{}', '{"Studio","Film","Kreatif"}', false, 'Rp 42 Miliar'),
('Cluster Modern Depok', 'Modern Cluster Housing', 'cluster-modern-depok', 'Perumahan', 'Depok, Jawa Barat', '8.000 m²', '20 Bulan', 2024, 'upcoming', 'PT Griya Makmur', 'Cluster 80 unit rumah modern minimalis di Depok.', 'Cluster eksklusif dengan 80 unit tipe 90-150 m², smart home system, dan taman komunal 2.000 m².', null, '{}', '{"Cluster","Modern","Depok"}', false, 'Rp 96 Miliar');

-- ── BLOG POSTS (20) ───────────────────────────────────────
INSERT INTO blog_posts (title, slug, excerpt, content, author, category, tags, published_at, featured, read_time, published) VALUES
('Tren Arsitektur Tropis Modern 2024', 'tren-arsitektur-tropis-2024', 'Eksplorasi tren terbaru arsitektur tropis yang memadukan material alami dan teknologi modern.', '## Tren Arsitektur Tropis 2024\n\nArsitektur tropis sedang mengalami renaissance. Biophilic design, material lokal premium, dan passive cooling menjadi standar baru.\n\n## Biophilic Design\n\nIntegrasi alam ke dalam bangunan bukan lagi kemewahan — ini kebutuhan. Taman vertikal, void dengan pohon besar, dan material organik menjadi standar.\n\n## Material Lokal\n\nBatu vulkanik, bambu rekayasa, dan kayu bersertifikat FSC semakin populer karena nilai estetika unik dan mendukung ekonomi lokal.', 'Ir. Andika Prasetyo', 'Arsitektur', '{"Tropis","Arsitektur","Desain","2024"}', '2024-03-15', true, 6, true),
('Green Building: Investasi Masa Depan', 'green-building-investasi', 'Bangunan hijau bukan tren — ini investasi cerdas yang memberikan penghematan energi signifikan.', '## Green Building Indonesia\n\nIndonesia memiliki potensi luar biasa dalam pengembangan bangunan hijau.\n\n## ROI yang Menarik\n\nMeskipun biaya konstruksi 5-15% lebih tinggi, penghematan operasional 10 tahun sudah melampaui investasi awal.\n\n## Sertifikasi\n\nLEED, Greenship, dan EDGE adalah tiga sertifikasi utama yang diakui di Indonesia. Masing-masing memiliki bobot penilaian berbeda.', 'Ir. Andika Prasetyo', 'Keberlanjutan', '{"Green Building","LEED","Investasi"}', '2024-02-20', true, 8, true),
('Revolusi BIM dalam Konstruksi Indonesia', 'revolusi-bim-konstruksi', 'Building Information Modeling merevolusi cara kita merencanakan dan membangun gedung.', '## BIM: Masa Depan Konstruksi\n\nBIM bukan sekadar software 3D — ini platform kolaborasi yang mengintegrasikan seluruh siklus hidup bangunan.\n\n## Manfaat Utama\n\nClash detection sebelum konstruksi menghemat biaya koreksi lapangan hingga 30%. Quantity takeoff akurat langsung dari model digital.\n\n## Implementasi di Indonesia\n\nAdopsi BIM di Indonesia masih 35% untuk proyek besar. Pemerintah mulai mewajibkan BIM untuk proyek infrastruktur di atas Rp 100 miliar.', 'Budi Hartono', 'Teknologi', '{"BIM","Teknologi","Digital"}', '2024-01-10', false, 5, true),
('Memilih Kontraktor yang Tepat', 'memilih-kontraktor-tepat', 'Panduan lengkap memilih kontraktor konstruksi terpercaya untuk proyek impian Anda.', '## Tips Memilih Kontraktor\n\nMemilih kontraktor yang salah bisa menjadi mimpi buruk. Berikut panduan komprehensif.\n\n## Cek Legalitas\n\nPastikan kontraktor memiliki SIUJK, SBU, dan NPWP aktif. Verifikasi di website LPJK.\n\n## Portofolio dan Referensi\n\nMinta daftar proyek yang pernah dikerjakan dan hubungi langsung klien sebelumnya.\n\n## Kontrak yang Jelas\n\nKontrak harus mencakup scope pekerjaan, jadwal, payment schedule, dan klausul penalti keterlambatan.', 'Budi Hartono', 'Tips', '{"Kontraktor","Tips","Panduan"}', '2024-03-01', false, 7, true),
('Fondasi Rumah: Pilih yang Tepat', 'fondasi-rumah-pilih-tepat', 'Panduan teknis memilih jenis fondasi yang sesuai dengan kondisi tanah dan beban bangunan.', '## Jenis-Jenis Fondasi\n\nFondasi adalah nyawa bangunan. Pemilihan yang tepat bergantung pada kondisi tanah dan beban struktur.\n\n## Fondasi Dangkal\n\nCocok untuk tanah keras dengan daya dukung tinggi. Tipe: pondasi batu kali, pondasi telapak (footplate), pondasi strouss.\n\n## Fondasi Dalam\n\nUntuk tanah lunak atau bangunan berat. Pilihan: tiang pancang, bored pile, mini pile. Harga lebih mahal tapi wajib untuk kondisi tertentu.', 'Dr. Maya Kusuma', 'Teknik', '{"Fondasi","Teknik","Struktur"}', '2024-02-05', false, 9, true),
('Desain Interior Rumah Tropis', 'desain-interior-tropis', 'Panduan menciptakan interior rumah tropis yang nyaman, sejuk, dan estetis.', '## Interior Tropis Modern\n\nRumah tropis yang baik bukan hanya soal AC yang kencang — melainkan desain yang merespons iklim.\n\n## Material Alami\n\nKayu, rotan, bambu, dan batu alam memberikan kehangatan visual sekaligus mengatur suhu ruangan secara alami.\n\n## Pencahayaan Alami\n\nMaksimalkan bukaan untuk cahaya dan angin. Skylight, clerestory window, dan courtyard adalah solusi elegan.', 'Dra. Sari Wijayanti', 'Desain Interior', '{"Interior","Tropis","Desain"}', '2024-01-25', false, 6, true),
('Inovasi Material Bangunan 2024', 'inovasi-material-bangunan-2024', 'Material konstruksi terbaru yang mengubah cara kita membangun — lebih kuat, ringan, dan ramah lingkungan.', '## Material Masa Depan\n\nIndustri konstruksi terus berinovasi. Berikut material terbaru yang wajib diketahui.\n\n## Mass Timber\n\nCross Laminated Timber (CLT) dan Glulam menawarkan kekuatan setara beton dengan jejak karbon jauh lebih rendah.\n\n## Beton Ultra-High Performance\n\nUHPC dengan kuat tekan >150 MPa memungkinkan elemen struktur lebih tipis dan bentang lebih panjang.', 'Dr. Maya Kusuma', 'Material', '{"Material","Inovasi","Teknologi"}', '2024-03-20', false, 5, true),
('Manajemen Proyek Konstruksi Modern', 'manajemen-proyek-konstruksi', 'Strategi manajemen proyek konstruksi yang efektif untuk memastikan tepat waktu dan anggaran.', '## Project Management Construction\n\nProyek konstruksi yang berhasil membutuhkan manajemen yang terstruktur dan komunikasi yang transparan.\n\n## Critical Path Method\n\nIdentifikasi aktivitas kritis yang menentukan durasi proyek. Keterlambatan pada jalur kritis langsung berdampak pada selesainya proyek.\n\n## Earned Value Management\n\nMonitor progres dengan membandingkan nilai pekerjaan yang sudah selesai (EV) terhadap biaya aktual (AC) dan rencana (PV).', 'Budi Hartono', 'Manajemen', '{"Manajemen","Proyek","Tips"}', '2024-02-15', false, 8, true),
('Renovasi Rumah: Panduan Lengkap', 'renovasi-rumah-panduan', 'Segala yang perlu Anda ketahui sebelum memulai renovasi rumah — dari perencanaan hingga finishing.', '## Rencanakan dengan Matang\n\nRenovasi tanpa perencanaan matang adalah resep malapetaka. Luangkan waktu untuk merancang dengan detail.\n\n## Tentukan Prioritas\n\nRenovasi seluruh rumah sekaligus jarang ideal. Prioritaskan area yang paling mempengaruhi kualitas hidup.\n\n## Budget dan Contingency\n\nSiapkan buffer 15-20% dari anggaran untuk biaya tak terduga. Ini bukan pilihan — ini keharusan.', 'Budi Hartono', 'Renovasi', '{"Renovasi","Panduan","Tips"}', '2024-01-05', false, 10, true),
('Teknologi Smart Home di Indonesia', 'teknologi-smart-home-indonesia', 'Perkembangan teknologi smart home di Indonesia dan bagaimana mengintegrasikannya dalam konstruksi baru.', '## Smart Home Indonesia\n\nEkosistem smart home semakin terjangkau. Ini saat yang tepat untuk mengintegrasikan teknologi ke dalam hunian baru.\n\n## Ecosystem Pilihan\n\nGoogle Home, Apple HomeKit, dan Amazon Alexa adalah tiga ekosistem utama. Pilih berdasarkan perangkat yang sudah dimiliki.\n\n## Integrasi Saat Konstruksi\n\nMasang conduit dan titik power yang tepat saat konstruksi jauh lebih mudah dan murah daripada retrofit kemudian.', 'Dra. Sari Wijayanti', 'Teknologi', '{"Smart Home","Teknologi","IoT"}', '2024-03-08', false, 6, true),
('Atap Rumah: Pilihan Material Terbaik', 'atap-rumah-material-terbaik', 'Perbandingan lengkap material atap rumah — dari genteng tanah liat hingga metal roofing modern.', '## Memilih Atap yang Tepat\n\nAtap adalah pertahanan pertama rumah Anda dari cuaca. Pilih dengan bijak.\n\n## Genteng Keramik\n\nKlasik dan tahan lama hingga 50 tahun. Berat namun memberikan insulasi termal yang baik.\n\n## Metal Roofing\n\nRingan, tahan bocor, dan bisa dipasang dengan kemiringan minimal. Pilihan terbaik untuk bentang lebar.', 'Dr. Maya Kusuma', 'Teknik', '{"Atap","Material","Teknik"}', '2024-02-28', false, 5, true),
('Landscape dan Taman: Melengkapi Hunian', 'landscape-taman-hunian', 'Panduan merancang taman dan landscape yang indah, fungsional, dan mudah dirawat.', '## Taman yang Hidup\n\nTaman bukan sekadar estetika — ini ruang hidup yang memperpanjang interior ke luar.\n\n## Tanaman Lokal\n\nGunakan tanaman lokal yang sudah teradaptasi dengan iklim setempat. Lebih mudah dirawat dan mendukung ekosistem lokal.\n\n## Sistem Irigasi\n\nDrip irrigation menghemat air hingga 60% dibanding penyiraman manual. Investasi yang sangat worthwhile.', 'Dra. Sari Wijayanti', 'Landscaping', '{"Taman","Landscape","Desain"}', '2024-01-18', false, 4, true),
('Keselamatan Kerja di Proyek Konstruksi', 'keselamatan-kerja-konstruksi', 'Standar K3 dalam konstruksi dan mengapa keselamatan pekerja adalah prioritas utama.', '## K3 dalam Konstruksi\n\nKonstruksi adalah salah satu industri paling berbahaya. Standar K3 yang ketat bukan pilihan — ini kewajiban hukum dan moral.\n\n## APD Wajib\n\nHelmet, harness, sepatu safety, rompi, dan kacamata pelindung adalah minimum yang harus dipatuhi di setiap lokasi.\n\n## Safety Culture\n\nBudaya keselamatan dimulai dari manajemen puncak. Safety officer yang berwenang dan pelatihan reguler adalah kunci.', 'Ir. Andika Prasetyo', 'K3', '{"K3","Keselamatan","Konstruksi"}', '2024-03-12', false, 7, true),
('Denah Rumah Type 36 yang Efisien', 'denah-rumah-type-36', 'Inspirasi denah rumah type 36 yang cerdas, fungsional, dan tetap terasa luas.', '## Memaksimalkan Type 36\n\nRumah type 36 tidak harus sempit. Dengan perencanaan cerdas, bisa sangat fungsional dan nyaman.\n\n## Open Plan Living\n\nHilangkan sekat antara ruang tamu, makan, dan dapur. Ruang terasa 2x lebih luas secara visual.\n\n## Storage Vertikal\n\nManfaatkan ketinggian ruangan. Rak hingga plafon, mezzanine untuk kamar tidur tambahan.', 'Dra. Sari Wijayanti', 'Desain', '{"Denah","Type 36","Efisien"}', '2024-02-10', false, 5, true),
('Plumbing dan Sanitasi Rumah Modern', 'plumbing-sanitasi-modern', 'Panduan sistem plumbing dan sanitasi yang benar untuk rumah sehat dan nyaman.', '## Sistem Plumbing yang Benar\n\nPlumbing yang buruk adalah sumber masalah tiada henti. Lakukan dengan benar sejak awal.\n\n## Material Pipa\n\nPPR untuk air bersih, PVC untuk air kotor, dan HDPE untuk saluran dalam tanah. Jangan campuraduk.\n\n## Septictank Biofilter\n\nSeptictank modern dengan biofilter mengolah limbah lebih sempurna dan tidak mencemari tanah sekitar.', 'Dr. Maya Kusuma', 'Teknik', '{"Plumbing","Sanitasi","Teknik"}', '2024-01-30', false, 6, true),
('Cat Rumah: Panduan Warna dan Jenis', 'cat-rumah-panduan-warna', 'Cara memilih cat yang tepat untuk interior dan eksterior rumah — warna, jenis, dan aplikasi.', '## Memilih Cat yang Tepat\n\nCat bukan sekadar warna — ini perlindungan dan ekspresi. Pilih dengan cermat.\n\n## Cat Eksterior vs Interior\n\nCat eksterior memiliki kandungan anti-UV dan anti-jamur yang lebih tinggi. Jangan gunakan cat interior untuk luar.\n\n## Psikologi Warna\n\nBiru menciptakan ketenangan, kuning memberi energi, putih memperluaskan ruang. Pahami efek warna sebelum memilih.', 'Dra. Sari Wijayanti', 'Finishing', '{"Cat","Warna","Interior"}', '2024-03-05', false, 4, true),
('Sistem Keamanan Rumah Modern', 'sistem-keamanan-rumah-modern', 'Panduan lengkap sistem keamanan rumah dari CCTV hingga smart lock dan alarm.', '## Rumah Aman di Era Modern\n\nAncaman keamanan semakin canggih. Sistem keamanan modern harus selangkah lebih maju.\n\n## CCTV IP Camera\n\nPilih kamera dengan resolusi minimal 4MP, night vision, dan kemampuan deteksi gerakan. Simpan rekaman di cloud.\n\n## Smart Lock\n\nKunci pintu dengan fingerprint, PIN, dan smartphone. Tidak perlu bawa kunci fisik dan bisa dibuka jarak jauh.', 'Budi Hartono', 'Keamanan', '{"Keamanan","CCTV","Smart Home"}', '2024-02-22', false, 5, true),
('Membangun Rumah dengan Budget Terbatas', 'membangun-rumah-budget-terbatas', 'Strategi cerdas membangun rumah impian dengan anggaran yang efisien tanpa mengorbankan kualitas.', '## Rumah Impian, Budget Nyata\n\nMembangun rumah dengan budget terbatas bukan berarti murahan. Ini soal prioritas dan kepintaran.\n\n## Desain Sederhana\n\nBentuk kotak sederhana lebih hemat 20-30% dibanding bentuk kompleks. Atap pelana lebih hemat dari atap limasan.\n\n## Material Lokal\n\nBatu bata lokal, pasir sungai, dan kayu lokal bisa menghemat signifikan tanpa mengorbankan kualitas.', 'Ir. Andika Prasetyo', 'Tips', '{"Budget","Tips","Hemat"}', '2024-01-08', false, 8, true),
('Perizinan Bangunan IMB dan PBG', 'perizinan-bangunan-imb-pbg', 'Panduan lengkap mengurus izin mendirikan bangunan (PBG) yang menggantikan IMB.', '## IMB Menjadi PBG\n\nSejak 2021, IMB resmi digantikan Persetujuan Bangunan Gedung (PBG) melalui PP No. 16 Tahun 2021.\n\n## Dokumen yang Dibutuhkan\n\nKTP, sertifikat tanah, gambar arsitektur, gambar struktur, gambar MEP, dan surat pernyataan arsitek.\n\n## Proses Online\n\nPBG kini diajukan melalui SIMBG (Sistem Informasi Manajemen Bangunan Gedung). Lebih cepat dan transparan.', 'Ir. Andika Prasetyo', 'Legal', '{"IMB","PBG","Perizinan"}', '2024-03-18', false, 9, true),
('Konstruksi Baja vs Beton: Mana yang Lebih Baik?', 'konstruksi-baja-vs-beton', 'Perbandingan mendalam antara konstruksi struktur baja dan beton bertulang untuk berbagai jenis bangunan.', '## Baja vs Beton\n\nPertanyaan klasik yang tidak memiliki jawaban universal. Pilihan tergantung kebutuhan spesifik proyek.\n\n## Keunggulan Baja\n\nLebih ringan, bentang lebih panjang, konstruksi lebih cepat, dan bisa dibongkar pasang. Ideal untuk gudang dan bentang besar.\n\n## Keunggulan Beton\n\nLebih tahan api, biaya material lebih rendah, ketahanan terhadap korosi lebih baik. Ideal untuk gedung bertingkat dan infrastruktur.', 'Dr. Maya Kusuma', 'Teknik', '{"Baja","Beton","Struktur"}', '2024-02-08', false, 7, true);

-- ── TEAM (20) ─────────────────────────────────────────────
INSERT INTO team (name, role, bio, "order") VALUES
('Ir. Andika Prasetyo, M.T.', 'Direktur Utama & Founder', 'Lebih dari 20 tahun pengalaman di industri konstruksi Indonesia. Alumni ITB Teknik Sipil dan S2 dari Delft University of Technology, Belanda. Pelopor penerapan green building di Indonesia.', 1),
('Dra. Sari Wijayanti, M.Arch.', 'Direktur Desain & Arsitektur', 'Arsitek terkemuka dengan portofolio 80+ proyek residensial dan komersial premium. Lulusan Universitas Indonesia dan Harvard Graduate School of Design. Pemenang IAI Award 2022.', 2),
('Budi Hartono, S.T., M.M.', 'Direktur Operasional', 'Spesialis manajemen konstruksi dengan keahlian value engineering dan optimalisasi proses. 18 tahun pengalaman mengelola proyek multi-miliar rupiah di seluruh Indonesia.', 3),
('Dr. Maya Kusuma, M.T.', 'Kepala Divisi Teknik', 'Insinyur struktur berpengalaman dalam desain gedung tinggi dan infrastruktur besar. Doktor Teknik dari UI dengan spesialisasi geoteknik dan fondasi dalam.', 4),
('Reza Firmansyah, S.T.', 'Senior Project Manager', 'Project Manager berpengalaman dengan rekam jejak 30+ proyek selesai tepat waktu. Certified PMP dan LEED AP. Spesialis konstruksi high-rise.', 5),
('Dewi Rahayu, S.Ars., M.Des.', 'Senior Interior Designer', 'Desainer interior dengan estetika tinggi dan pemahaman mendalam tentang kebutuhan klien premium. Lulusan Parsons School of Design New York.', 6),
('Hendro Susanto, S.T.', 'Kepala QA/QC', 'Bertanggung jawab memastikan setiap pekerjaan memenuhi standar kualitas tertinggi. ISO 9001 Lead Auditor dengan pengalaman 15 tahun di quality control.', 7),
('Rina Marliani, S.E., M.B.A.', 'Direktur Keuangan', 'Ahli keuangan konstruksi dengan keahlian dalam financial planning, cost control, dan laporan keuangan proyek. Lulusan FEUI dan Wharton School of Business.', 8),
('Agus Setiawan, S.T.', 'Manajer Mechanical & Electrical', 'Insinyur M&E berpengalaman dalam sistem HVAC, plumbing, dan instalasi listrik gedung tinggi. 12 tahun di industri dengan proyek-proyek landmark.', 9),
('Nurul Huda, S.T., M.T.', 'Structural Engineer Senior', 'Insinyur struktur spesialis bangunan tahan gempa. Menggunakan software analisis struktur terkini untuk desain yang akurat dan aman.', 10),
('Wahyu Pratama, S.Kom.', 'Kepala Divisi BIM', 'Pelopor implementasi BIM di perusahaan. Mengelola tim drafter dan BIM coordinator untuk memastikan koordinasi antar disiplin yang sempurna.', 11),
('Fitri Handayani, S.Ars.', 'Arsitek Senior', 'Spesialis desain fasad dan selubung bangunan. Pengalaman di Singapura dan Malaysia sebelum bergabung membawa perspektif internasional.', 12),
('Dedi Kurniawan, S.T.', 'Manajer Procurement', 'Mengelola pengadaan material dan vendor dengan memastikan kualitas terbaik pada harga kompetitif. Jaringan supplier luas di seluruh Indonesia.', 13),
('Anita Wulandari, S.H.', 'Legal & Compliance Manager', 'Memastikan seluruh operasional perusahaan sesuai regulasi. Berpengalaman dalam hukum konstruksi, kontrak, dan perizinan bangunan.', 14),
('Bayu Adiputra, S.T.', 'Site Manager Senior', 'Mengawasi pelaksanaan di lapangan dengan teliti. Pengalaman langsung di 25+ proyek dari fondasi hingga finishing. Ahli problem solving lapangan.', 15),
('Indah Permatasari, S.Kom.', 'IT & Digital Manager', 'Mengelola infrastruktur IT dan transformasi digital perusahaan. Implementasi ERP, project management software, dan CRM yang terintegrasi.', 16),
('Tono Wibisono, S.T., M.T.', 'Landscape Architect', 'Merancang taman dan landscape yang harmonis dengan arsitektur bangunan. Mengutamakan tanaman lokal dan sistem irigasi hemat air.', 17),
('Sri Wahyuni, S.E.', 'HR & General Affairs Manager', 'Mengelola SDM 120+ karyawan dengan budaya kerja positif dan sistem pengembangan karir yang terstruktur. Fokus pada employee wellbeing.', 18),
('Gunawan Setiadi, S.T.', 'K3 Manager', 'Memastikan standar keselamatan tertinggi di seluruh lokasi proyek. Zero accident selama 5 tahun berturut-turut sebagai pencapaian kebanggaan.', 19),
('Melinda Putri, S.Ars.', 'Junior Architect', 'Arsitek muda berbakat lulusan terbaik Universitas Parahyangan. Spesialisasi desain 3D rendering dan presentasi visual yang memukau.', 20);

-- ── TESTIMONIALS (20) ─────────────────────────────────────
INSERT INTO testimonials (name, role, company, content, rating, featured) VALUES
('Hendro Sugiarto', 'CEO', 'PT Nexus Property Indonesia', 'Rofimain Konstruksi membangun gedung kami tepat waktu dan sesuai anggaran. Kualitas jauh melebihi ekspektasi. Manajemen proyek profesional dan komunikasi sangat transparan.', 5, true),
('Jennifer Tan', 'Owner', 'Horizon Hospitality Group', 'Resort Uluwatu kami menjadi kenyataan berkat keahlian Rofimain. Tantangan konstruksi di tebing yang sangat teknis berhasil diatasi dengan tetap menjaga jadwal.', 5, true),
('Eko Prabowo', 'Direktur', 'PT Green Land Developer', 'Tim Rofimain memahami konsep green building dengan sangat baik. Inovasi mereka menghemat biaya operasional jangka panjang secara signifikan.', 5, true),
('Ratna Dewi', 'Homeowner', '', 'Membangun villa di Puncak bersama Rofimain adalah pengalaman menyenangkan. Sangat memperhatikan detail dan komunikasi sangat baik. Hasilnya luar biasa!', 5, true),
('Bapak Sutanto', 'Direktur Utama', 'PT Alam Sutera Realty', 'Pembangunan 50 unit ruko selesai sesuai jadwal. Finishing sangat rapi dan material berkualitas tinggi. Kami akan kembali menggunakan jasa Rofimain untuk proyek berikutnya.', 5, false),
('Dr. Hendra Gunawan', 'Kepala Dinas', 'Dinas PUPR Bekasi', 'Pembangunan jembatan Kali Bekasi berjalan lancar. Standar teknis terpenuhi dan laporan progress sangat detail. Rekanan yang sangat profesional.', 5, false),
('Sinta Wulandari', 'Owner', 'Pavilion Group Bali', 'Kompleks villa kami di Seminyak dikerjakan dengan sangat baik. Desain yang dieksekusi sempurna dan setiap detail diperhatikan. Sangat memuaskan.', 4, false),
('Drs. Bambang Soeharto', 'Rektor', 'Global Education Group', 'Kampus sekolah internasional kami dibangun dengan standar tinggi. Tim sangat kooperatif dan selalu mencari solusi terbaik untuk setiap tantangan.', 5, false),
('Ibu Hartini', 'Homeowner', '', 'Renovasi rumah kami selesai tepat waktu dan hasilnya melebihi ekspektasi. Tim sangat sopan dan lokasi kerja selalu bersih. Recommended!', 5, false),
('Michael Chen', 'Managing Director', 'Archipelago International', 'Hotel kami di Labuan Bajo dikerjakan dengan standar internasional yang sangat tinggi. Kualitas tidak kalah dengan kontraktor asing namun dengan harga jauh lebih kompetitif.', 5, false),
('Pak Ridwan', 'Direktur', 'Siloam Hospitals Group', 'Pembangunan RS Siloam Bogor memenuhi semua standar teknis medis yang sangat ketat. Tim benar-benar memahami kebutuhan khusus fasilitas kesehatan.', 5, false),
('Lisa Santoso', 'Homeowner', '', 'Rumah impian kami akhirnya terwujud. Rofimain sangat membantu dari proses desain hingga finishing. Setiap saran mereka sangat berharga.', 5, false),
('Bapak Hartono', 'CEO', 'PT Bukit Sentul', 'Pengembangan perumahan Sentul berjalan sesuai masterplan. Tim sangat terorganisir dan laporan keuangan proyek sangat transparan.', 4, false),
('Nadia Rahman', 'Homeowner', '', 'Proses pembangunan sangat menyenangkan karena tim selalu update progress harian. Hasilnya sangat memuaskan, rumah terasa nyaman dan berkualitas.', 5, false),
('Pak Yusuf', 'Direktur', 'PT Logindo Samudramakmur', 'Gudang logistik kami selesai 2 minggu lebih awal dari jadwal. Sistem otomasi yang diintegrasikan berjalan sempurna. Sangat profesional.', 5, false),
('Bu Dewi Kartini', 'Kepala Sekolah', 'International School BSD', 'Fasilitas sekolah kami sangat memukau. Laboratorium, studio, dan amphiteater dikerjakan dengan detail yang luar biasa. Murid dan guru sangat senang.', 5, false),
('Alex Gunawan', 'Owner', 'Produksi Nusantara Films', 'Studio film kami dikerjakan dengan pemahaman teknis yang sangat baik. Sistem akustik dan pencahayaan sempurna. Tim sangat responsif terhadap kebutuhan khusus.', 5, false),
('Pak Santoso', 'Homeowner', '', 'Cluster hunian kami selesai lebih cepat dari perkiraan. Kualitas bangunan sangat solid dan finishing sangat rapi. Investasi terbaik kami.', 4, false),
('Ibu Margaretha', 'Homeowner', '', 'Senang sekali bekerja dengan tim Rofimain. Sangat sabar menjelaskan setiap tahapan dan selalu terbuka untuk masukan. Hasil akhir sangat memuaskan.', 5, false),
('Bapak Wahyudi', 'Direktur Teknis', 'PT KIK Development', 'Kawasan industri Karawang dikerjakan dengan standar internasional. Sistem utilitas dan IPAL berfungsi sempurna. Rekan kerja yang sangat diandalkan.', 5, false);

-- Update settings
INSERT INTO settings (key, value) VALUES
  ('site_name', 'Rofimain Konstruksi'),
  ('tagline', 'Membangun Impian, Menciptakan Warisan'),
  ('description', 'Perusahaan konstruksi premium terpercaya dengan pengalaman lebih dari 15 tahun dalam membangun hunian mewah, gedung komersial, dan infrastruktur berkualitas tinggi di Indonesia.'),
  ('phone', '+62 21 5555 7890'),
  ('whatsapp', '+6281234567890'),
  ('email', 'info@rofimain.com'),
  ('address', 'Menara Sudirman, Lt. 12 Suite A, Jl. Jenderal Sudirman Kav. 60, Jakarta Selatan 12190'),
  ('city', 'Jakarta'),
  ('instagram', 'https://instagram.com/rofimain'),
  ('linkedin', 'https://linkedin.com/company/rofimain'),
  ('facebook', 'https://facebook.com/rofimain'),
  ('youtube', 'https://youtube.com/@rofimain')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
